export enum Role {
  PUBLIC_USER = 'PUBLIC_USER',
  STUDENT = 'STUDENT',
  CHAPTER_MEMBER = 'CHAPTER_MEMBER',
  CHAPTER_OFFICER = 'CHAPTER_OFFICER',
  CHAPTER_ADMIN = 'CHAPTER_ADMIN',
  FACULTY_COORDINATOR = 'FACULTY_COORDINATOR',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
}

export enum ChapterStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum EventStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  PUBLISHED = 'PUBLISHED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

export enum EventType {
  TECHNICAL_TALK = 'TECHNICAL_TALK',
  WORKSHOP = 'WORKSHOP',
  HACKATHON = 'HACKATHON',
  SYMPOSIUM = 'SYMPOSIUM',
  CONFERENCE = 'CONFERENCE',
  COMPETITION = 'COMPETITION',
}

export enum EventFormat {
  IN_PERSON = 'IN_PERSON',
  ONLINE = 'ONLINE',
  HYBRID = 'HYBRID',
}

export enum RegistrationStatus {
  CONFIRMED = 'CONFIRMED',
  WAITLISTED = 'WAITLISTED',
  CANCELLED = 'CANCELLED',
  ATTENDED = 'ATTENDED',
}
